---
abstract: ~
author:
  - 'Kazuho Oku'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
  Test::TCP: 0.15
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Starlet
name: Starlet
no_index:
  directory:
    - inc
    - t
requires:
  Parallel::Prefork: 0.07
  Plack: 0.992
  Server::Starter: 0.06
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
